### ISSUE TITLE
Exceptions raised in FX Application Thread are not displayed / managed in dev mode

### ISSUE THREAD

**Issue by CodeSimcoe** [quarkiverse/quarkus-fx#107]

**Comment by CodeSimcoe** [comment]
@Eng-Fouad Do you have the same issue ? Do you want to have a look ?

**Comment by Eng-Fouad** [comment]
> @Eng-Fouad Do you have the same issue ? Do you want to have a look ?

I don't have the same issue. Do you have a stacktrace or a reproducer?

**Comment by CodeSimcoe** [comment]
Only in dev mode, to be precise

**Comment by CodeSimcoe** [comment]
Issue was related to https://github.com/quarkusio/quarkus/issues/44653

**Comment by CodeSimcoe** [comment]
Fixed in 0.9.1 as fixed by Quarkus 3.15.3
