### ISSUE TITLE
Stylesheet live reloading is not working using Gradle

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkiverse/quarkus-fx#119]
When Gradle is used with the following configurations:

```
quarkus.fx.views-root=views/
quarkus.fx.source-resources=src/main/
quarkus.fx.target-resources=build/
```

I got this line printed in logs:

> Stylesheet live reload : substituting 'file:/C:/Users/fouad/IdeaProjects/quarkusfx-demo/build/resources/main/views/main/main.css' with 'src/main/resources/main/views/main/main.css'

and this exception:
```
Caused by: java.nio.file.NoSuchFileException: src\main\resources\main\views\main
```

'src/main/resources/main/views/main/main.css' should be 'src/main/resources/views/main/main.css'

**Comment by CodeSimcoe** [comment]
Hello, do you have a repo somewhere with reproducer ? ty

**Comment by Eng-Fouad** [comment]
> Hello, do you have a repo somewhere with reproducer ? ty

https://github.com/Eng-Fouad/quarkus-fx-0.9-bug

**Comment by CodeSimcoe** [comment]
Please update your configuration to the following :

```properties
quarkus.fx.views-root=views/
#quarkus.fx.source-resources=src/main/
quarkus.fx.target-resources=build/resources/main/
```

If not clear, we can improve documentation.

**Comment by Eng-Fouad** [comment]
> Please update your configuration to the following :
> 
> ```ini
> quarkus.fx.views-root=views/
> #quarkus.fx.source-resources=src/main/
> quarkus.fx.target-resources=build/resources/main/
> ```
> 
> If not clear, we can improve documentation.
> 
> ![image](https://private-user-images.githubusercontent.com/110094118/391950640-aefc0502-f3fe-4e68-97da-0eacf32cdb8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjY3NDgsIm5iZiI6MTczMzIyNjQ0OCwicGF0aCI6Ii8xMTAwOTQxMTgvMzkxOTUwNjQwLWFlZmMwNTAyLWYzZmUtNGU2OC05N2RhLTBlYWNmMzJjZGI4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QxMTQ3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmMyYTRkYTBlMzExNmVjYTBkM2U4YjAxMjFmNDVjNWQ4N2ExYmZhZWFjZTQ4Njg3YzA2YzhkNWE4MDQ1MTM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oEv3nu7qfidsF9_sS4eSlT14o6mY-TIkz5s3VkUHQTU)

That works, thanks. It would be helpful if we add a note to docs for Gradle users.
