### ISSUE TITLE
Cannot release due to tests requiring display

### ISSUE THREAD

**Issue by CodeSimcoe** [quarkiverse/quarkus-fx#26]
Can't pass release workflow
https://github.com/quarkiverse/quarkus-fx/actions/runs/7816761315/job/21323090134

![image](https://github.com/quarkiverse/quarkus-fx/assets/110094118/a4eb00b0-1ab9-43b0-85be-9be5667ac7cf)

@gastaldi What do you think ? We need a graphic environment to run JavaFX tests :/

**Comment by gastaldi** [comment]
I'd suggest to disable tests in the release workflow until a better solution is found

**Comment by ghazyami** [comment]
@CodeSimcoe we have tests running on build pipeline with `xvfb` that did not work with release pipeline?
https://github.com/quarkiverse/quarkus-fx/blob/853268a4c8ae40ceb83171d38c7a94b510fc6f46/.github/workflows/build.yml#L58-L61

**Comment by ghazyami** [comment]
`Maven release` step is not using `coactions/setup-xvfb@v1` that will setup `xvfb` before executing maven commands

https://github.com/quarkiverse/quarkus-fx/blob/853268a4c8ae40ceb83171d38c7a94b510fc6f46/.github/workflows/release.yml#L58-L66

**Comment by ghazyami** [comment]
Check #33

**Comment by CodeSimcoe** [comment]
PR merged, we'll see next release !

**Comment by CodeSimcoe** [comment]
Meanwhile, closing the issue.
Will re-open it if any problem is encountered after that

**Comment by CodeSimcoe** [comment]
Fix is effective and 0.2.0 is on its way thanks @ghazyami 🥇
