### ISSUE TITLE
Load FXML view file by convention

### ISSUE THREAD

**Issue by hantsy** [quarkiverse/quarkus-fx#43]
Followed the PR #20, I would like there is an annotation `@FxView ` which can attach the FXML file to the controller directly, and no need loading it via FxmlLoader. 

```java
@FxView // load MasterView.fxml by default in the same package, or specify the location manually.
// also discover the resources files, css, images etc.
@Dependent
class MasterViewController {}
```

Thus the codes the codes are similar to the MVC architecture. 

Ideally, the controller is a CDI bean to process the business logic, the JavaFX FXML file is used for UI layout, also can access the controller properties/method via EL like Jakarta Faces/Facelets.

I have used [JavaFX Weaver core moudle](https://github.com/rgielen/javafx-weaver) to integrate CDI/Weld with JavaFX in my example project before, https://github.com/hantsy/cargotracker-regapp/blob/master/src/main/java/org/eclipse/cargotrakcer/regapp/ui/HandlingReportController.java#L28, which provides a similar feature.

**Comment by CodeSimcoe** [comment]
Hello,
this is indeed a close need of PR #20, except that using annotations makes sense that it belongs in this extension.
I'm working on it, and will propose a PR soon

**Comment by hantsy** [comment]
More simply, make the `@FxView` includes a specific `CustomScope` for FXML view. Thus we can remove `@Dependent` here.

**Comment by CodeSimcoe** [comment]
Have a look at branch `fx-views` if you want to.
And its associated sample (fxviews)

Any feedback appreciated

**Comment by CodeSimcoe** [comment]
Hello @hantsy , you reviewed PR #20 but that was not my point.
My proposition is on branch `fx-views`, no PR yet.
I can create a draft PR if you want.

**Comment by hantsy** [comment]
It looks great for me.

Please create a PR for it, thus other developers will have a chance to discuss on the changes.

**Comment by CodeSimcoe** [comment]
> It looks great for me.
> 
> Please create a PR for it, thus other developers will have a chance to discuss on the changes.

Please have a look at 0.4.0, any feedback appreciated

**Comment by CodeSimcoe** [comment]
Marking this as closed / resolved.
