### ISSUE TITLE
Support injecting HostServices

### ISSUE THREAD

**Issue by hallvard** [quarkiverse/quarkus-fx#52]
If I understand it correctly, a HostServices instance can only be acquired using the Application object, but this object isn't available when using this extension. Is it possible to make the HostServices "singleton" available as an application scoped object?

**Comment by CodeSimcoe** [comment]
Hello @hallvard 
I see several ways to achieve this :
1. Add a static accessor method in `io.quarkiverse.fx.FxApplication` to get the `HostServices` instance
2. Add the `HostServices` instance in the `FxStartupEvent` or `FxPreStartupEvent`
3. Provide an injectable bean with the `HostServices` instance

What are your thoughts ?
1. seems pretty straightforward...

**Comment by CodeSimcoe** [comment]
See #53 
Looks more relevant to me to provide similar access than `Application`.
Making an injectable instance limits the usage

**Comment by hallvard** [comment]
Making it available through a static method goes against DI thinking, IMO. I would prefer making it an injectable (ApplicationScoped or Singleton) instance. I could also be added to the FxStartupEvent but that makes it less accessible other places.

**Comment by CodeSimcoe** [comment]
I'm wondering how we can make it injectable given that it is lazily created and only available at a given point in the lifecycle (when `Application` is created)

**Comment by CodeSimcoe** [comment]
@hallvard : I figured out something, can you check PR if this fits your needs ?
best regards
Clement

**Comment by hallvard** [comment]
That seems perfect! The solution with an event that is observed, should give a proper ordering, and the build step makes sure Quarkus knows about the producer (if I understand this correctly).
I you're curious, the app that needs this is an llm workbench with a markdown view for documentation, and I want to support links to external sites: https://github.com/kantega/llm-starter-and-workbench/tree/main/wb/src/main/java/no/hal/wb/views/markdown
I'm probably going to move the wb and wb-fx modules into a separate repository (since it's should be reusable) and make a simpler example app with documentation that points to quarkus-fx.

**Comment by CodeSimcoe** [comment]
I have release 0.4.2
https://central.sonatype.com/artifact/io.quarkiverse.fx/quarkus-fx/0.4.2

Don't hesitate if you have some needs.

**Comment by hallvard** [comment]
Works as expected! Tested in https://github.com/hallvard/wb-fx
