### ISSUE TITLE
Custom resource root per @FxView

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkiverse/quarkus-fx#74]
Currently, one can specify a custom root for resources in `application.properties`, something like:

```
quarkus.fx.fxml-root=/fxml/
quarkus.fx.style-root=/style/
quarkus.fx.bundle-root=/i18n/
```

It would be nice if we can specify the custom root per @FxView which will override the default in `application.properties`, something like:

```
@FxView(fxmlRoot="/core/fxml/", styleRoot="/core/style/", bundleRoot="/core/i18n/")
@Singleton
public class CoreController {...}

@FxView(fxmlRoot="/registration/fxml/", styleRoot="/registration/style/", bundleRoot="/registration/i18n/")
@Singleton
public class RegistrationController {...}

@FxView(fxmlRoot="/login/fxml/", styleRoot="/login/style/", bundleRoot="/login/i18n/")
@Singleton
public class LoginController {...}

```

```
resources
   |___ /core
   |       |___ /fxml
   |       |___ /style
   |       |___ /i18n
   |___ /registration
   |       |___ /fxml
   |       |___ /style
   |       |___ /i18n
   |___ /login
           |___ /fxml
           |___ /style
           |___ /i18n
```

**Comment by CodeSimcoe** [comment]
Looks like a good overall idea, allowing to have better organized project.
But it's kind of verbose.
We could use some "convention over configuration" : in your example you always use fxml, style and i18n directories.
I think the extension could, in order :
- Look for files as it is currently done
- Look in default directories : {viewName}/fxml, {viewName}/style and {viewName}/i18n
- Look for specific directories

**Comment by Eng-Fouad** [comment]
> I think the extension could, in order :
> 
> * Look for files as it is currently done
> * Look in default directories : {viewName}/fxml, {viewName}/style and {viewName}/i18n
> * Look for specific directories

Yes I like this idea.

**Comment by CodeSimcoe** [comment]
Do you want me to complete the work (I can do it :) ) ?

**Comment by Eng-Fouad** [comment]
> Do you want me to complete the work (I can do it :) ) ?
> 
> Also, the default directories names could be fxml, style and i18n but this could be overridden.

Sure, go ahead.

**Comment by CodeSimcoe** [comment]
I think I'll limit to something like :

```
resources
   |___ /core
   | ______core.fxml
   | ______core.css
   | ______core.properties
   |___ /registration
   | ______etc..
   |___ /login
 ```

**Comment by CodeSimcoe** [comment]
Just out of curiosities, what project are you working on :) ?

**Comment by Eng-Fouad** [comment]
> Just out of curiosities, what project are you working on :) ?

Unfortunately, it is not a public project :(

**Comment by Eng-Fouad** [comment]
> I think I'll limit to something like :
> 
> ```
> resources
>    |___ /core
>    |       |_____core.fxml
>    |       |_____core.css
>    |       |_____core.properties
>    |___ /registration
>    | ______etc..
>    |___ /login
> ```

What if a module has multiple fxml files? It would be something like:

```
resources
   |___ /core
   |       |_____core.fxml
   |       |_____header.fxml
   |       |_____body.fxml
   |       |_____footer.fxml
   |       |_____core.css
   |       |_____core.properties
```

versus

```
resources
   |___ /core
   |       |____ /fxml
   |                |_____core.fxml
   |                |_____header.fxml
   |                |_____body.fxml
   |                |_____footer.fxml
   |___ /style
   |       |_____core.css
   |___ /i18n
   |       |_____core.properties
```

WDYT?

**Comment by CodeSimcoe** [comment]
#88

```
src/
└── main/
    └── resources/
        └── views/
            ├── Home/
            │   ├── Home.fxml
            │   ├── Home.css
            │   └── Home.properties
            └── About/
                ├── About.fxml
                ├── About.css
                └── About.properties
```

**Comment by CodeSimcoe** [comment]
#88 : closing
