### ISSUE TITLE
Inject Controller from ViewB into ViewA

### ISSUE THREAD

**Issue by manuelwallrapp** [quarkiverse/quarkus-fx#89]
Hi

I have a ViewA.fxml which includes ViewB.fxml in the fxml code. 
Each view has it's own Controller ViewAController and ViewBController. Both are annotated with @Dependent
They both are initialized correctly. How can I access from ViewAController methods the instance of ViewBController? If I do it with @Inject, I will not get the Bean which is initialized by JavaFx rather the Bean from Quarkus which has no injected view objects.

It would be nice if a working example would be available in the repository.

**Comment by manuelwallrapp** [comment]
If I do it like this it seems to work:
FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("ViewB.fxml"));
fxmlLoader.load();
fxmlLoader.getController().accessViewBControllerMethods();

**Comment by CodeSimcoe** [comment]
Hello,
do you have a sample project somewhere that I can have a look at ?

**Comment by CodeSimcoe** [comment]
I managed to have the issue here using FxView and Dependent.
Works with Singleton though (no proxy)

**Comment by Eng-Fouad** [comment]
In JavaFX, you can inject controller of the included view using `@FXML`, with adding `Controller` as a suffix to the injected controller name. Something like:

ViewA.fxml:
```
<?xml version="1.0" encoding="UTF-8"?>
<?import javafx.scene.layout.BorderPane?>
<BorderPane xmlns:fx="http://javafx.com/fxml" fx:controller="a.b.ViewAController">
    <center>
        <fx:include fx:id="viewB" source="viewB.fxml"/>
    </center>
</BorderPane>
```
ViewA.fxml:
```
<?xml version="1.0" encoding="UTF-8"?>
<?import javafx.scene.layout.BorderPane?>
<BorderPane xmlns:fx="http://javafx.com/fxml" fx:controller="a.b.ViewBController">
    <center>
        <Label text="Hello World"/>
    </center>
</BorderPane>
```

ViewAController.java:
```
public class ViewAController {
    @FXML ViewBController viewBController; // (viewB + Controller)
}
```

**Comment by manuelwallrapp** [comment]
@CodeSimcoe thank you, with @Singleton instead of @Dependent it works like a charm

@Eng-Fouad thank you as well, I didn't know I can do it like this as well. But the singleton way works for me, since there I have all the Beans injected the Quarkus way.
